"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"

version = 3

[upgrade]
    auto = false
    interval = "168h"

[palette]
    foreground = "#C0CAF5"
    cyan = "#27A1B9"
    red = "#FF007C"
    orange = "#FF9E64"
    green = "#1ABC9C"

[[blocks]]
    type = "prompt"
    alignment = "left"

    [[blocks.segments]]
        style = "plain"
        background = "transparent"
        foreground = "p:cyan"
        type = "text"
        template = "❱ "

[[blocks]]
    type = "rprompt"
    overflow = "hide"

    [[blocks.segments]]
        style = "plain"
        background = "transparent"
        foreground = "p:foreground"
        type = "path"
        template = "[  {{ .Path }} ]"

        [blocks.segments.properties]
            style = "agnoster_short"
            max_depth = 2

        [[blocks.segments]]
            style = "plain"
            background = "transparent"
            foreground = "p:cyan"
            type = "git"
            template = "[ {{ .HEAD }} ]"

            [blocks.segments.properties]
                branch_icon = " "

    [[blocks.segments]]
        style = "plain"
        background = "transparent"
        foreground_templates = [
            "{{if eq .Code 0}}p:green{{else}}{{if ge .Code 128}}p:orange{{else}}p:red{{end}}{{end}}",
        ]
        type = "executiontime"
        template = "{{if gt .Ms 0}}[  {{ .FormattedMs }} ]{{end}}"

        [blocks.segments.properties]
            always_enabled = true


[secondary_prompt]
    foreground = "p:cyan"
    background = "transparent"
    template = "❱❱ "
